# Generated by Django 4.0.3 on 2022-04-04 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, verbose_name='Text')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('rating', models.IntegerField(default=0, verbose_name='Rating')),
                ('status', models.CharField(choices=[('new', 'New'), ('moderated', 'Moderated')], default='new', max_length=15, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='Session key')),
                ('rating', models.IntegerField(choices=[(1, 'up'), (-1, 'down')], verbose_name='Rating')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='webapp.quote', verbose_name='Quote')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'ordering': ('quote', 'rating'),
            },
        ),
    ]
